###########################################################################################################
# Playbook: Plexzner Setup
###################################################################################################################

---
- name: Plexzner
  hosts: all
  remote_user: root
  gather_facts: true
  vars:
    create_user: ruler
    # Plex related variables
    tautulli_install: true
    plexupdate_install: true
    # Transmission variables
    transmission_rpc_port: 9991
    transmission_rpc_auth_required: true
    transmission_group: wheel
    transmission_url: '/baconbits/'
    transmission_user: ruler
    transmission_password: "{{ lookup('env', 'TRANSMISSION_PASSWORD') }}"
    transmission_rpc_whitelist_enabled: false
    transmission_watch_dir: '/home/ruler/torrents'
    transmission_incomplete_dir: '/home/ruler/.incomplete'
    transmission_download_dir: '/home/ruler/downloads'
    # sshfs
    remote_media_directory: '/'
    ssh_username: u215565
    ssh_password: "{{ lookup('env', 'SSHFS_PASSWORD') }}"
    ssh_server: u215565.your-storagebox.de
    ssh_media_directory: '/mnt/the-hub'
    # resilio sync
    resilio_password: "{{ lookup('env', 'RESILIO_PASSWORD') }}"

  roles:
    - base
    - plexmediaserver
    - transmission
    - sshfs
    - resiliosync
