---
- include_tasks: plex.yml
  when: (ansible_os_family == 'RedHat') or
        (ansible_os_family == 'Debian')

- name: Include tautulli
  include_role:
    name: tautulli
  when: tautulli_install

- name: Include plexupdate
  include_role:
    name: plexupdate
  when: plexupdate_install
