---
- name: Install git & wget
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
    - wget
    - git

- name: Clone plexupdate repository
  git:
    repo: https://github.com/mrworf/plexupdate.git
    dest: "{{ plexupdate_install_location }}"
    version: "{{ plexupdate_version }}"

- name: Create desired config
  template:
    src: plexupdate/plexupdate.conf.j2
    dest: "{{ plexupdate_config_location }}"

- name: Install latest plex with plexupdate
  command: "{{ plexupdate_install_location }}/plexupdate.sh --config {{ plexupdate_config_location }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  changed_when: "'already installed' not in plexupdate_output.stdout"
  register: plexupdate_output
  notify: restart plex

- name: Reload systemD daemon
  systemd:
    name: plexmediaserver
    daemon_reload: true
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7") or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 15.04) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8)

- name: Autostart Plex
  service:
    name: plexmediaserver
    enabled: true
  notify: restart plex
